# Generated by Django 5.2.4 on 2025-08-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_engine_car_enginepower_car_madein_car_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
