# Generated by Django 5.2.4 on 2025-08-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_review_delete_car_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviemr_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
