# Generated by Django 5.2.4 on 2025-08-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_review_reviemr_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='star_ratting',
            field=models.IntegerField(default=0),
        ),
    ]
