# Generated by Django 5.2.4 on 2025-08-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_rename_name_review_review_review_star_ratting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviemr_name',
            new_name='reviewr_name',
        ),
    ]
