# Generated by Django 5.2.4 on 2025-08-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_rename_reviemr_name_review_reviewr_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
