# Generated by Django 5.2.4 on 2025-08-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='star_ratting',
            new_name='rating',
        ),
    ]
