# Generated by Django 5.2.4 on 2025-08-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
