# Generated by Django 5.2.4 on 2025-08-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
