# Generated by Django 5.2.4 on 2025-08-15 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0017_alter_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
