# Generated by Django 5.2.4 on 2025-08-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=100)),
                ('profile_picture', models.ImageField(default=0, upload_to='author_images/')),
                ('background_image', models.ImageField(blank=True, default=0, null=True, upload_to='anime_backgrounds/')),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0)),
                ('image', models.ImageField(upload_to='anime_images/')),
                ('description', models.TextField(default=0)),
                ('release_date', models.DateField(default=0)),
                ('genre', models.CharField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='animes', to='anime.author')),
            ],
        ),
    ]
