# Generated by Django 5.2.4 on 2025-08-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='cars/')),
                ('author', models.CharField()),
                ('publishyear', models.IntegerField()),
            ],
        ),
    ]
