# Generated by Django 5.2.4 on 2025-08-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_authors_delete_author_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='dateofbirth',
            field=models.DateField(),
        ),
    ]
