# Generated by Django 5.2.4 on 2025-08-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='created_at',
            new_name='timeStamp',
        ),
    ]
