# Generated by Django 5.2.4 on 2025-08-18 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
