# Generated by Django 5.2.4 on 2025-08-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_authors_country_book_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='country',
        ),
    ]
