# Generated by Django 5.2.4 on 2025-08-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_remove_book_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='country',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
