# Generated by Django 5.2.4 on 2025-08-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='generation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='ram',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='ssd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
